services:
  # 1. El Servidor Web (Tu aplicación Laravel)
  - type: web
    name: mi-app-web
    runtime: php
    plan: free
    region: ohio 
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan storage:link
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: mi-app-web
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pserv
          name: mi-base-de-datos
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: mi-base-de-datos
          property: port
      - key: DB_DATABASE
        fromService:
          type: pserv
          name: mi-base-de-datos
          property: databaseName
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: mi-base-de-datos
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: mi-base-de-datos
          property: password
      - key: APP_KEY
        sync: false

  # 2. La Base de Datos
  - type: pserv
    name: mi-base-de-datos
    plan: free
    engine: postgresql # <-- La palabra clave correcta es 'engine'
    engineVersion: 15 # <-- La palabra clave correcta es 'engineVersion'