services:
  - type: web
    name: financepwa
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
      php artisan storage:link
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: financepwa
          property: url
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: finance
          property: connectionString
      - key: APP_KEY
        sync: false

  - type: pserv
    name: finance
    runtime: postgres
    plan: free